apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authapi
          image: sugaprivate/authprod:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-env
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: authapi-service
spec:
  type: ClusterIP
  selector:
    app: authapi
  ports:
    - port: 9000
      targetPort: 9000